"""
Send the daily reorder briefing email via Gmail API.

Uses a Google Service Account with domain-wide delegation OR
a Gmail OAuth2 credential (service-account impersonation).

Subject: "⚡ Winterfell Reorder Alert — [DATE] — [N] SKUs Need Action"
Sends HTML email with:
  - Summary counts (critical / warning / healthy)
  - RED SKUs table first, then YELLOW
  - Claude recommendation per SKU
  - Total estimated reorder cost
  - Auto-generated footer
"""

import base64
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from google.oauth2.service_account import Credentials
from googleapiclient.discovery import build

import config
from config import logger

_SCOPES = ["https://www.googleapis.com/auth/gmail.send"]


def _get_gmail_service():
    creds = Credentials.from_service_account_file(
        config.GOOGLE_SERVICE_ACCOUNT_JSON,
        scopes=_SCOPES,
    )
    # Delegate to the sender address so Gmail sends on their behalf
    delegated = creds.with_subject(config.GMAIL_SENDER)
    return build("gmail", "v1", credentials=delegated, cache_discovery=False)


def _urgency_badge(tier: str) -> str:
    if tier == "CRITICAL":
        return '<span style="background:#e53935;color:#fff;padding:2px 8px;border-radius:4px;font-weight:bold;">🔴 CRITICAL</span>'
    if tier == "WARNING":
        return '<span style="background:#fdd835;color:#333;padding:2px 8px;border-radius:4px;font-weight:bold;">🟡 WARNING</span>'
    return '<span style="background:#43a047;color:#fff;padding:2px 8px;border-radius:4px;font-weight:bold;">🟢 HEALTHY</span>'


def _sku_row_html(s: dict) -> str:
    days = s.get("days_remaining", 9999)
    days_str = "∞" if days >= 9999 else f"{days}d"
    rec = s.get("claude_action_note") or s.get("claude_trend_note") or "—"
    price = s.get("estimated_cost", 0)

    return f"""
    <tr>
      <td style="padding:6px 10px;font-family:monospace;">{s.get('sku','')}</td>
      <td style="padding:6px 10px;">{s.get('product_name','')}</td>
      <td style="padding:6px 10px;text-align:center;">{s.get('current_stock',0)}</td>
      <td style="padding:6px 10px;text-align:center;">{round(s.get('daily_velocity_14d',0),2)}</td>
      <td style="padding:6px 10px;text-align:center;font-weight:bold;">{days_str}</td>
      <td style="padding:6px 10px;text-align:center;">{s.get('claude_recommended_qty') or s.get('reorder_qty',0)}</td>
      <td style="padding:6px 10px;text-align:right;">BDT {price:,.0f}</td>
      <td style="padding:6px 10px;">{rec}</td>
    </tr>"""


def _build_sku_table(skus: list[dict]) -> str:
    if not skus:
        return "<p><em>None</em></p>"

    rows_html = "".join(_sku_row_html(s) for s in skus)
    return f"""
    <table border="0" cellspacing="0" cellpadding="0"
           style="width:100%;border-collapse:collapse;font-size:13px;">
      <thead>
        <tr style="background:#333;color:#fff;">
          <th style="padding:8px 10px;text-align:left;">SKU</th>
          <th style="padding:8px 10px;text-align:left;">Product</th>
          <th style="padding:8px 10px;text-align:center;">Stock</th>
          <th style="padding:8px 10px;text-align:center;">Velocity/day</th>
          <th style="padding:8px 10px;text-align:center;">Days Left</th>
          <th style="padding:8px 10px;text-align:center;">Order Qty</th>
          <th style="padding:8px 10px;text-align:right;">Est. Cost</th>
          <th style="padding:8px 10px;text-align:left;">Recommendation</th>
        </tr>
      </thead>
      <tbody>{rows_html}</tbody>
    </table>"""


def build_email_html(all_skus: list[dict], run_date: str) -> str:
    critical = [s for s in all_skus if s.get("urgency_tier") == "CRITICAL"]
    warning = [s for s in all_skus if s.get("urgency_tier") == "WARNING"]
    healthy = [s for s in all_skus if s.get("urgency_tier") == "HEALTHY"]

    total_cost = sum(
        s.get("estimated_cost", 0)
        for s in all_skus
        if s.get("urgency_tier") in ("CRITICAL", "WARNING")
    )

    return f"""<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;max-width:1100px;margin:0 auto;color:#222;">
  <div style="background:#1a1a2e;color:#fff;padding:20px 30px;border-radius:8px 8px 0 0;">
    <h1 style="margin:0;font-size:22px;">⚡ Winterfell Reorder Alert</h1>
    <p style="margin:4px 0 0;opacity:0.8;">{run_date} &nbsp;|&nbsp; Auto-generated by Winterfell Reorder Engine</p>
  </div>

  <div style="background:#f5f5f5;padding:16px 30px;border-bottom:1px solid #ddd;">
    <strong>Summary:</strong>
    &nbsp; 🔴 Critical: <strong>{len(critical)}</strong>
    &nbsp;&nbsp; 🟡 Warning: <strong>{len(warning)}</strong>
    &nbsp;&nbsp; 🟢 Healthy: <strong>{len(healthy)}</strong>
    &nbsp;&nbsp;&nbsp; Total SKUs: <strong>{len(all_skus)}</strong>
    &nbsp;&nbsp;&nbsp; | &nbsp; Estimated reorder cost (RED+YELLOW):
    <strong>BDT {total_cost:,.0f}</strong>
  </div>

  <div style="padding:20px 30px;">

    <h2 style="color:#c62828;">🔴 Critical — Immediate Action Required ({len(critical)} SKUs)</h2>
    {_build_sku_table(critical)}

    <br/>
    <h2 style="color:#f9a825;">🟡 Warning — Order This Week ({len(warning)} SKUs)</h2>
    {_build_sku_table(warning)}

  </div>

  <div style="background:#f0f0f0;padding:14px 30px;border-top:1px solid #ddd;
              font-size:12px;color:#666;border-radius:0 0 8px 8px;">
    Auto-generated by Winterfell Reorder Engine &nbsp;|&nbsp;
    Data sources: WooCommerce · Nuport · Zoho Books &nbsp;|&nbsp;
    Intelligence: Claude (claude-sonnet-4-20250514)
  </div>
</body>
</html>"""


def send_email(all_skus: list[dict]) -> None:
    """Build and send the daily reorder briefing email."""
    critical_count = sum(1 for s in all_skus if s.get("urgency_tier") == "CRITICAL")
    warning_count = sum(1 for s in all_skus if s.get("urgency_tier") == "WARNING")
    action_count = critical_count + warning_count

    run_date = datetime.now().strftime("%d %b %Y")
    subject = (
        f"⚡ Winterfell Reorder Alert — {run_date} — {action_count} SKUs Need Action"
    )

    html_body = build_email_html(all_skus, run_date)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = config.GMAIL_SENDER
    msg["To"] = config.REORDER_EMAIL
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode("utf-8")

    try:
        service = _get_gmail_service()
        service.users().messages().send(
            userId="me", body={"raw": raw}
        ).execute()
        logger.info("Email sent to %s. Subject: %s", config.REORDER_EMAIL, subject)
    except Exception as exc:
        logger.error("Gmail send failed: %s", exc)
        raise
